import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount } from 'wagmi';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LaunchToken from '../components/LaunchToken'

const Home: NextPage = () => {
  const account = useAccount()

  return (
    <div className={styles.container}>
      <Head>
        <title>QuibleMint</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {account.isConnected && <LaunchToken accountAddress={account.address!} />}
      </main>
    </div>
  );
};

export default Home;
